//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System.Globalization;
using System.Resources;

namespace LoreLoom.Cli.Resources;

internal class Resources
{
    private static ResourceManager? _resourceManager;

    private static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager("LoreLoom.Cli.Resources.Resources", typeof(Resources).Assembly);

    private static CultureInfo? Culture => null;

    private static string GetString(string name) => ResourceManager.GetString(name, Culture) ?? name;

    // App
    public static string AppTitle => GetString("AppTitle");
    public static string AppSubtitle => GetString("AppSubtitle");

    // Auth
    public static string AuthRegisterOrLogin => GetString("AuthRegisterOrLogin");
    public static string AuthRegister => GetString("AuthRegister");
    public static string AuthLogin => GetString("AuthLogin");
    public static string AuthUsername => GetString("AuthUsername");
    public static string AuthPassword => GetString("AuthPassword");
    public static string AuthRegisterSuccess => GetString("AuthRegisterSuccess");
    public static string AuthLoginSuccess => GetString("AuthLoginSuccess");
    public static string AuthError => GetString("AuthError");
    public static string WelcomeBack => GetString("WelcomeBack");

    // Main Menu
    public static string MenuTitle => GetString("MenuTitle");
    public static string MenuCharacters => GetString("MenuCharacters");
    public static string MenuJoinGame => GetString("MenuJoinGame");
    public static string MenuCreateGame => GetString("MenuCreateGame");
    public static string MenuRanking => GetString("MenuRanking");
    public static string MenuLanguage => GetString("MenuLanguage");
    public static string MenuLogout => GetString("MenuLogout");
    public static string MenuExit => GetString("MenuExit");
    public static string SelectLanguage => GetString("SelectLanguage");
    public static string LanguageChanged => GetString("LanguageChanged");

    // Characters
    public static string CharactersTitle => GetString("CharactersTitle");
    public static string CreateNewCharacter => GetString("CreateNewCharacter");
    public static string GoBack => GetString("GoBack");
    public static string CharacterName => GetString("CharacterName");
    public static string CharacterBackstory => GetString("CharacterBackstory");
    public static string StatStrength => GetString("StatStrength");
    public static string StatWit => GetString("StatWit");
    public static string StatCharisma => GetString("StatCharisma");
    public static string StatsInstruction => GetString("StatsInstruction");
    public static string CharacterCreated => GetString("CharacterCreated");
    public static string NoCharacters => GetString("NoCharacters");
    public static string Level => GetString("Level");
    public static string XP => GetString("XP");
    public static string StatsError => GetString("StatsError");

    // Games
    public static string GameTitle => GetString("GameTitle");
    public static string GameSetting => GetString("GameSetting");
    public static string GameResourceName => GetString("GameResourceName");
    public static string GameMaxPlayers => GetString("GameMaxPlayers");
    public static string GameIsPublic => GetString("GameIsPublic");
    public static string GameLanguage => GetString("GameLanguage");
    public static string GameCreated => GetString("GameCreated");
    public static string GameInviteCode => GetString("GameInviteCode");
    public static string SelectCharacter => GetString("SelectCharacter");
    public static string NoCharOption => GetString("NoCharOption");
    public static string PlayerName => GetString("PlayerName");
    public static string PublicGames => GetString("PublicGames");
    public static string NoPublicGames => GetString("NoPublicGames");
    public static string EnterGameId => GetString("EnterGameId");
    public static string JoinedGame => GetString("JoinedGame");
    public static string WaitingForStart => GetString("WaitingForStart");
    public static string StartGame => GetString("StartGame");
    public static string WaitForPlayers => GetString("WaitForPlayers");
    public static string PlayersInGame => GetString("PlayersInGame");
    public static string GameStarted => GetString("GameStarted");

    // Turn
    public static string YourTurn => GetString("YourTurn");
    public static string NotYourTurn => GetString("NotYourTurn");
    public static string EnterAction => GetString("EnterAction");
    public static string WaitingForDm => GetString("WaitingForDm");
    public static string ResourceBar => GetString("ResourceBar");
    public static string DmSays => GetString("DmSays");
    public static string ResourceCost => GetString("ResourceCost");
    public static string PressEnter => GetString("PressEnter");

    // Game Over
    public static string GameOverVictory => GetString("GameOverVictory");
    public static string GameOverDefeat => GetString("GameOverDefeat");
    public static string Postmortem => GetString("Postmortem");
    public static string Results => GetString("Results");
    public static string Player => GetString("Player");
    public static string XpEarned => GetString("XpEarned");
    public static string Points => GetString("Points");
    public static string ExportQuestion => GetString("ExportQuestion");
    public static string ExportSaved => GetString("ExportSaved");

    // Errors
    public static string ErrorConnection => GetString("ErrorConnection");
    public static string ErrorGeneric => GetString("ErrorGeneric");

    // Ranking
    public static string RankingTitle => GetString("RankingTitle");
    public static string RankingEmpty => GetString("RankingEmpty");
    public static string Rank => GetString("Rank");
    public static string GamesPlayed => GetString("GamesPlayed");
}
